language: node_js

node_js:  
  - "node"

sudo: required

services:
  - docker

env:
  - HOST_PORT=3000 CONTAINER_PORT=3000

script:
  - docker-compose up --exit-code-from test --build test mongo 

cache:
  directories:
  - "node_modules"