language: node_js

sudo: required

services:
  - docker

env:
  - HOST_PORT=3000 CONTAINER_PORT=3000

script:
  - docker-compose up --exit-code-from test test mongo 

cache:
  directories:
  - "node_modules"