version: '3.7'
services:
  web:
    image: node:11
    container_name: api-sigarra-web
    build: .
    ports:
      - 3000:3000
    volumes:
       - ./app:/usr/src/app
    links:
      - mongodb
    command: yarn start
  mongodb:
    image: mongo:4.0
    container_name: api-sigarra-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
