version: "3"
services:
  web-prod:
    build: 
      context: .
    volumes:
      - ./src:/usr/src/api-sigarra/src
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    environment:
      - PORT=${CONTAINER_PORT}
    links:
      - mongo
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - PORT=${CONTAINER_PORT}
    volumes:
      - ./src:/usr/src/api-sigarra/src
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    links:
      - mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - PORT=${CONTAINER_PORT}
    volumes:
      - ./src:/usr/src/api-sigarra/src
      - ./test:/usr/src/api-sigarra/test
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"