version: '3.7'
services:
  web:
    image: node:11
    container_name: api-sigarra-web
    build: .
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
       - .:/usr/app
    links:
      - mongodb
    command: yarn test
  mongodb:
    image: mongo:4.0
    container_name: api-sigarra-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
