version: "3"
services:
  web-prod:
    build: 
      context: .
    volumes:
      - ./lib:/usr/lib/api-sigarra/lib
      - ./web:/usr/lib/api-sigarra/web
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    environment:
      - PORT=${CONTAINER_PORT}
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/prod
    links:
      - mongo
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - PORT=${CONTAINER_PORT}
      - NODE_ENV=development
    volumes:
      - ./web:/usr/lib/api-sigarra/web
      - ./lib:/usr/lib/api-sigarra/lib
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    links:
      - mongo
    depends_on:
      - mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
      args:
        TEST_PORT: ${CONTAINER_PORT}
    environment:
      - PORT=${CONTAINER_PORT}
      - NODE_ENV=test
    volumes:
      - ./lib:/usr/lib/api-sigarra/lib
      - ./web:/usr/lib/api-sigarra/web
      - ./test:/usr/lib/api-sigarra/test
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  parser:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    command: npm run parser
    volumes:
      - ./lib:/usr/lib/api-sigarra/lib
  processor:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    command: npm run processor
    volumes:
      - ./lib:/usr/lib/api-sigarra/lib
      - ./processors:/usr/lib/api-sigarra/processors
    environment:
      - MONGO_URI=mongodb://mongo:27017/prod
    depends_on:
      - mongo